export {default as Home} from './home/Home'
export {default as Auth} from './auth/Auth'
export {default as Main} from './dashboard/Dashboard'
export {default as Pets} from './Pets/Pets'
export {default as Inventory} from './inventory/inventory'
export {default as Profile} from './profile/Profile'
export {default as homeDashboard} from './home-dashboard/HomeDashboard'
