export {default as Home} from './home/Home'
export {default as Auth} from './auth/Auth'
export {default as Main} from './dashboard/Dashboard'
export {default as Clients} from './clients/PetInfo'
export {default as Inventory} from './inventory/inventory'
export {default as Profile} from './profile/Profile'