export {default as Home} from './home/Home'
export {default as Auth} from './auth/Auth'
export {default as Main} from './dashboard/Dashboard'
export {default as Clients} from './clients/Clients'
export {default as PetProfile} from './petProfile/PetProfile'